nacl_test_tnl2_release.nexe: nacl_test_tnl2.cc
	/Users/markf/Work/gg/nativeclient/native_client/src/third_party/nacl_sdk/mac/sdk/nacl-sdk/bin/nacl-g++ nacl_test_tnl2.cc -O2 -I../tnl2 -I../../torque_sockets -Ilibtomcrypt/src/headers -Ilibtommath -lav -lsrpc -lpthread -lm -o nacl_test_tnl2_release.nexe 
