nacl_test_tnl2.nexe: nacl_test_tnl2.cc
	/Users/markf/Work/gg/nativeclient/native_client/toolchain/mac_x86/sdk/nacl-sdk/bin/nacl-g++ nacl_test_tnl2.cc -O2 -DXP_UNIX -I../../nativeclient -I../tnl2 -I../../torque_sockets -I../test_tnl2 -Ilibtomcrypt/src/headers -Ilibtommath -Llibtommath -Llibtomcrypt -ltomcrypt -ltommath -lm -lgoogle_nacl_imc -lgoogle_nacl_npruntime -lgoogle_nacl_pgl -lgoogle_nacl_gpu -lpthread -lsrpc -o nacl_test_tnl2.nexe 
	
	
